# Copyright (C) 2022 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

on:
  push:
  pull_request:
  schedule:
    - cron: '0 17 * * 3' #At 17:00 on Wednesday UTC

name: Continuous integration

jobs:
  run:
    name: Run scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: cargo run
        working-directory: scraper
